# Generated by Django 3.2.19 on 2023-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='choice_pictures'),
        ),
        migrations.AddField(
            model_name='choice',
            name='preparation',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
