# Generated by Django 4.2.2 on 2023-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_choice_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_pictures/'),
        ),
    ]
