# Generated by Django 3.2.19 on 2023-06-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_auto_20230611_1248'),
        ('choices', '0005_alter_choice_picture'),
    ]

    operations = [
    ]
